### PR TITLE
addListener to mediaQuery print to redraw the chart

### PR DESCRIPTION
**Pull request by frnk94**
The problem is that while the chart adjusts to resize events in the browser, those events are not triggered when creating a print. This PR resize the chart upon print. Im open to discussion

### CODE REVIEW

**Comment by kirjs** [comment]
Hi Francois, thanks for the PR.
Instead of having this code in ReachHighchats can we instead create a wrapper component which would do the same, and then  document how it works [here](https://github.com/kirjs/react-highcharts/blob/master/recipes.md)? 

You can access the chart [like this](https://github.com/kirjs/react-highcharts#accessing-highcharts-api-after-render).

It could look like this: 
```html
<RedrawOnPrint>
  <ReactHighcharts config = {config}>
</RedrawOnPrint>
```

wdyt?

**Comment by frnk94** [comment]
Yea it would make sense since a lot of user dont really care about print. Should we just document how the wrapper component should work or make it available through the lib itself ?

**Comment by kirjs** [comment]
I'd do both, given most of the code is written already.

**Comment by frnk94** [comment]
Want me to update this PR or you will do it ?

**Comment by kirjs** [comment]
If you have time please do that, otherwise I'll do that in a few weeks.

**Comment by frnk94** [comment]
alright I will push something tonight or tomorrow

**Comment by frnk94** [comment]
@kirjs What do you think of this ?

**Comment by frnk94** [comment]
@kirjs the `<div>` make sure it would render nicely even if someone do
```jsx
<RedrawOnPrint>
    <ReactHighcharts config = {config} />
</RedrawOnPrint>
```

**Comment by frnk94** [comment]
> Please get rid of a new line
> Please get add a new line

@kirjs Sorry im not sure to understand you on this ?

**Comment by kirjs** [comment]
I think it's all good, don't worry about the new lines.

**Comment by kirjs** [comment]
Thanks a lot!

**Pull request merged**
