### PR TITLE
Update highcharts to 4.2.0

### PR DESCRIPTION
**Pull request by kirjs**

### CODE REVIEW

**Comment by kirjs** [comment]
cc @JohnPhoto

**Comment by JohnPhoto** [comment]
Yeah got some input here too if this one is not solved before I get the time to help out. They seems to have redone the loading/init api.

**Comment by kirjs** [comment]
It seems to work in demos and pass all the tests, a quick sanity code review would help if you have a second.

**Comment by kirjs** [comment]
Fixed, thanks!

**Pull request merged**
