### PR TITLE
Update highcharts to 5.0.2

### PR DESCRIPTION
**Pull request by ShinyChang**
highcharts 5.0.2 fixed lots of bugs

### CODE REVIEW

**Comment by kirjs** [comment]
What's the point of having updated highcharts in the lib?
Why not just update it in your project?
Are you still using bundled version?

**Comment by nordicbondpricing** [comment]
Hi Kirill

Just to be clear as to how this works:
Is the only way to use the unbundled version of react-highcharts, to set highcharts as a global variable?

**Comment by elmoro666** [comment]
Hi Kirill

Just to be clear as to how this works:
Is the only way to use the unbundled version of react-highcharts, to set highcharts as a global variable?

**Comment by kirjs** [comment]
@elmoro666 It supports AMD, you could also use webpack, or AMD.

**Comment by elmoro666** [comment]
Thanks Kirill. I use webpack. I just haven't been able to make it work properly. For example, if I have react-highcharts at version 11.0.0 (which is bundled with highcharts 5.0.2), and I have installed highcharts version 4.2.4 and I write:

import Highcharts from "highcharts";
import ReactHighcharts from "react-highcharts"; 

Then I end up with both version 4.4.2 and 5.0.2 in my bundle file. I have seen somewhere that you must set 
global.highcharts... to make it work, that's what I meant.

**Comment by kirjs** [comment]
Interesting, that's not how that is supposed to work.
Are you sure bundled version of RH is not required anywhere else in the code?

**Comment by elmoro666** [comment]
Yes I just removed all entry points except on in my webpack file, and built it. Still two versions of highcharts in there. If you want to I can make an example for you

**Comment by kirjs** [comment]
Please do

**Comment by elmoro666** [comment]
Here is an example. I dont' have a lot of experience creating repos for others, so let me know if it is not understandable. 

https://github.com/elmoro666/HichartExample

**Comment by szj123456** [comment]
Hi Kirill
    How to get the charts svg ?
    I have do like this but doesn't work  the chart can not find the getSVG() function
    import ReactHighcharts  from "react-highcharts";
    import React, {Component, PropTypes} from "react";

    export class newMarketCharts extends Component {
        constructor(props) {
        super(props);
        this.state = {
            "windowsWidth": 500
        };
    }
    componentDidMount() {  
        let svgs = this.refs.chart.getSVG();  //can not access getSVG() method 
        
    }
    render() {
           <ReactHighcharts config={config} ref="chart"  />
        }
    }

**Comment by elmoro666** [comment]
@szj123456 

According to the docs you need the exporting module:

http://api.highcharts.com/highcharts/Chart.getSVG

**Comment by kirjs** [comment]
Thanks @elmoro666, I'll take a look later this week

**Comment by elmoro666** [comment]
Hi @kirjs, have you had a chance to look at this issue?

**Comment by kirjs** [comment]
Hey, @elmoro666 I took a quick look, and don't understand how the both versions gets in. 
See if you can require ReactHighcharts.js file directly?

Sorry for being slow to respond, I'm travelling ATM

**Comment by elmoro666** [comment]
Ok , you don't have to look into this anymore. I have found another solution. thanks.

**Comment by Jakehp** [comment]
@elmoro666 can you close this then?

**Comment by elmoro666** [comment]
Hi Jakehp. It's not my thread. I just hijacked it :)

**Comment by Jakehp** [comment]
doh @ShinyChang can you close this?

**Pull request closed without merging**
