### PR TITLE
Upgrade highcharts to ^6.0.0

### LINKED ISSUE #333: Update to Highcharts 6
[Blog post](https://www.highcharts.com/blog/news/announcing-highcharts-6/) about the new version.

### PR DESCRIPTION
**Pull request by mindjuice**
Tested with version 6.0.2 of highcharts, highstock and boost
Fixes #333

### CODE REVIEW

**Comment by mindjuice** [comment]
Looks like the saucelabs authentication failed.

**Comment by m-allanson** [comment]
@mindjuice see also #340 :)

**Comment by mindjuice** [comment]
Cool...just want it to land already!

**Comment by kirjs** [comment]
I'll hopefully will take a look over the weekend, is someone with time wants to help maintaining this to speed things up please lmk!

**Comment by kirjs** [comment]
Thanks a lot for your PR @mindjuice, I'm closing this as it does exactly the same thing as #340.

**Pull request closed without merging**
