### PR TITLE
clarify use of highcharts-release

### PR DESCRIPTION
**Pull request by mblakele**
It took some digging into the demo examples before I saw how to upgrade from a pre-3 release. I hope these edits to the instructions clarify things a little.

### CODE REVIEW

**Comment by kirjs** [comment]
Hi Michael, thanks a lot for creating the PR documenting your findings, 

One minor thing: 
Using `highcharts-release` is just one of the ways to get Highcharts in the codebase, and won't cover all use cases. 

I see the need to document it's usage, but how about we move the example to a separate file, and then have a link with something like `see here how to get highcharts-release in your code base to use with react-highcharts`?

**Comment by mblakele** [comment]
Absolutely, but I thought I would share my notes about what worked in my situation. Feel free to use any of that's useful, and edit to suit.

**Comment by kirjs** [comment]
Thanks a lot!

**Comment by kirjs** [comment]
The contents of this commit went into recipes section: https://github.com/kirjs/react-highcharts/blob/master/recipes.md

**Pull request closed without merging**
