### PR TITLE
Added highstocks

### PR DESCRIPTION
**Pull request by joshhornby**
```highstock.src``` ships with Highchart and Highstock charts. Hence why we can include it here.

### CODE REVIEW

**Comment by Kureev** [comment]
Cool, but I think it should be like a "type" property and switch-case function which solves it. fyi @kirjs

**Comment by joshhornby** [comment]
Agreed that's a nicer solution. 

Will refactor.

**Comment by kirjs** [comment]
Hi Josh, 

Thanks for the pull request, as far as I understand is similar to highcharts.more?

If so, this pr https://github.com/kirjs/react-highcharts/pull/3 and this commit could also help:
https://github.com/kirjs/react-highcharts/commit/87c0b5b024ba85e221512ce40f86f5cdae2691f6

**Comment by joshhornby** [comment]
Think this would then relate to https://github.com/kirjs/react-highcharts/issues/9

I'll leave it until you've had a chance to look at this issue and I think once you solve one this would be much easier to refactor.

**Comment by kirjs** [comment]
Hi Josh, 

Looks like Highstocks unlike `more` and `maps` contains the code from highcharts.

My recommendation for adding `highstock` would be to create a `Highstock` component in the root folder which would require `highstock` instead of `highcharts`. 

The api would be as follows: 
```
var Highstock = require('react-highcharts/highstock');
React.render(
  <Highstock config={config}></Highstock>,
  document.getElementById('test')
);
```

Please let me know what you think. 
I'm actually open for suggestions here.

**Comment by joshhornby** [comment]
@kirjs seems like a decent solution to me.

**Comment by kirjs** [comment]
@joshhornby would you be interested in doing a PR?

**Comment by joshhornby** [comment]
@kirjs sure I'll sort ASAP

**Comment by joshhornby** [comment]
@kirjs Just been looking at this, seems highstock isn't included in core package we are using https://github.com/highslide-software/highcharts-release

**Comment by kirjs** [comment]
Are there any existing packages which include what we need?
Don't see anything bad with having package as a part of the project as long as it doesn't go into the highcharts bundle

**Comment by joshhornby** [comment]
https://github.com/golyakov/highstock-browserify might do the trick, not sure how we'd get webpack to not bundle it together with the highcharts stuff.

**Comment by kirjs** [comment]
What about pulling the repo from github like the way we did before #20 got in?
Also would be worth creating an issue on the highstock repo maybe?

**Comment by joshhornby** [comment]
I have found https://github.com/highslide-software/highstock-release. This could work, although I don't have much time currently to implement the solution.

**Comment by kirjs** [comment]
Josh, 
I played with highstocks-release, it's awkward, but seems to work, let me know if you'll have a few minutes to take a glance at the code, would be nice.

**Comment by kirjs** [comment]
fixed in #29

**Pull request closed without merging**
