### PR TITLE
add Highmaps support

### PR DESCRIPTION
**Pull request by nash716**
I want to use Highmaps with React.
This allows users to render maps.

Usage:
```js
var Highcharts = require('react-highcharts');
require('react-highcharts/highmaps');
```

```jsx
<Highcharts type="map" config={config}></Highcharts>
```

### CODE REVIEW

**Comment by kirjs** [comment]
Hi Nash, Thanks a lot for the PR, did you have a chance to test it?

**Comment by joshhornby** [comment]
Won't this cause this issue? 

https://github.com/kirjs/react-highcharts/issues/9

**Comment by kirjs** [comment]
I guess that's something I'd have to do with `more.js` to close #9 
That would be an API change and would require version bump. 

Feel free to do a PR, or I'll try to do that over the weekend

**Comment by kirjs** [comment]
upd: Josh, I misread your comment.
Highcharts is a bit confusing in this way: `more` and `map`, are add-ons to highcharts, while highstock is a separate entity. 
I just have to get it all together and figure out all possible permutations, something I'm planning to do over the weekend.

**Comment by nash716** [comment]
Hi @kirjs, thanks for your comment, and I'm sorry for the late reply.
I tested my code in my project by installing react-highcharts with `npm i nash716/react-highcharts`

I think that my code doesn't cause #9.

a.jsx
```
var Highcharts = require('react-highcharts');
```

b.jsx
```
var Highcharts = require('react-highcharts');
require('react-highcharts/highmaps');
```

c.jsx
```
var Highcharts = require('react-highcharts');
require('react-highcharts/highmaps');
```

`react-highcharts/highmaps` was required twice. On the other hand, `a.jsx` requires `react-highcharts` only. It works without any errors.

But the big overhaul project is in progress (#20), I think I should wait for it to finish.
What do you think?

**Comment by kirjs** [comment]
Hi Nash, no worries, I agree on #20, let's get it in, and see how the merge would look like.

**Comment by thientran1707** [comment]
@kirjs can you update the readme.md to show how to use highmap with a map?

**Comment by kirjs** [comment]
The pull request has not been merged yet.
@nash716 Can you get it on top of master and see if it needs some updating?

**Comment by nash716** [comment]
Hi,
I've been tied up with work, couldn't grasp the change.
And what is worse, I'm busy for a while...
I'll make time to update my code.

@thientran1707 
If you are in a hurry, you can use this feature **for now**.
Please run `$ npm i nash716/react-highcharts`.
Readme is [here.](https://github.com/nash716/react-highcharts/blob/master/README.md)

**Comment by gmeroz** [comment]
Hi,
Any chance this pull request will be merged soon? 
Thanks,
Gil

**Comment by nash716** [comment]
I tried to update my code, but some problems were found.

`highmaps-release` doesn't contain map module.
`highmaps-release` contains `highmaps.src.js`, and `highmaps.src.js` has `Highcharts`.
The map module is not available.
Codes like below will cause [this](http://www.highcharts.com/errors/16) ( #39 )

a.jsx
```
var Highcharts = require('react-highcharts');
```

b.jsx
```
var Highmaps = require('react-highcharts/highmaps');
```

**Comment by kirjs** [comment]
Fixed in #45

**Pull request closed without merging**
