### PR TITLE
Expose the Highchart chart object

### PR DESCRIPTION
**Pull request by aldendaniels**
Usage:

```javascript
class MyComponent extends React.Component {
  componentDidMount() {
    let chart = this.refs.chart.getChart();
    // Can now manipulate chart via chart.method()
  }

  render() {
    return <Highcharts config={config} ref="chart"></Highcharts>;
  }
}
```

### CODE REVIEW

**Comment by kirjs** [comment]
Looks good for me, can you please add the usage example to the readme when you have a chance?
Or I can do it over the weekend

**Comment by aldendaniels** [comment]
@kirjs Done

**Comment by kirjs** [comment]
great, thanks a lot

**Comment by aldendaniels** [comment]
Awesome! Thanks for merging so quickly.

**Comment by aldendaniels** [comment]
Could you also publish this to NPM?

**Comment by kirjs** [comment]
version 1.0.3 should be in

**Comment by aldendaniels** [comment]
:+1:

**Pull request merged**
