### PR TITLE
If a chart is already present it must be destroyed

### PR DESCRIPTION
**Pull request by pinturic**
To me this was causing this problem: https://github.com/kirjs/react-highcharts/issues/384

Moreover for sure many resources were  not released but on the contrary they were accumulating.

### CODE REVIEW

**Comment by kirjs** [comment]
Good catch

**Comment by kirjs** [comment]
Thanks a lot @pinturic 
Mind writing a test for this? Otherwise I can do it some time later

**Comment by pinturic** [comment]
My pleasure @kirjs . Let me know if you need something more.

**Comment by pinturic** [comment]
Do you plan do merge this?

**Comment by pinturic** [comment]
I don't think you created a tag after PR has been accepted.

**Comment by pinturic** [comment]
I don't think you created a tag after PR has been merged.

**Pull request merged**
