### PR TITLE
Support highcharts render callback

### PR DESCRIPTION
**Pull request by dbergey**
This allows us to use the Highcharts renderer to draw on the chart as in their examples.

### CODE REVIEW

**Comment by kirjs** [comment]
Looks great, what happened to the tests though?

**Comment by dbergey** [comment]
Oops. That should fix it.

**Comment by kirjs** [comment]
Thanks, will you have a chance to add an example to the readme?
Otherwise I'll do that some time over the weekend.

**Comment by kirjs** [comment]
Thanks a lot! 8.0.3

**Pull request merged**
