### PR TITLE
Update to Highcharts v6

### LINKED ISSUE #333: Update to Highcharts 6
[Blog post](https://www.highcharts.com/blog/news/announcing-highcharts-6/) about the new version.

### PR DESCRIPTION
**Pull request by m-allanson**
The unit tests and demo both look 👍 here.

Closes #333

### CODE REVIEW

**Comment by m-allanson** [comment]
@madsonic I've updated this to include the version number in the README, to match your changes in #341

**Comment by firasdib** [comment]
Whats holding this back?

**Comment by joeellis** [comment]
Would be great to see this get updated.  6.0 has some bug fixes that would make my life much easier

**Comment by madsonic** [comment]
not to mention more chart types!

**Comment by chernetsov** [comment]
Any updates here? we want new plots too!

**Comment by firasdib** [comment]
@kirjs Can you please look at this PR?

**Comment by kirjs** [comment]
Hopefully will have some time this weekend

**Comment by joeellis** [comment]
@kirjs Thank you for the merge and your hard work!

**Comment by kirjs** [comment]
thanks a lot @m-allanson! 
This has been merged in as v15.0.0

**Pull request merged**
